"""add api_keys table

Revision ID: 6998a682b470
Revises: d7a69cb8a125
Create Date: 2026-08-18 00:57:26.303150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6998a682b470'
down_revision: Union[str, None] = 'd7a69cb8a125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='FK lógica a users.id (sin FK para evitar acoplamiento)'),
    sa.Column('bot_id', sa.String(length=100), nullable=False, comment='Identificador del bot al que pertenece esta clave'),
    sa.Column('exchange', sa.String(length=50), nullable=False, comment="Nombre del exchange (ej: 'hyperliquid')"),
    sa.Column('encrypted_api_key', sa.Text(), nullable=False, comment='API key cifrada con Fernet (base64-urlsafe)'),
    sa.Column('encrypted_api_secret', sa.Text(), nullable=False, comment='API secret cifrado con Fernet (base64-urlsafe)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Si False, la clave está revocada y no debe usarse'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_bot_id'), 'api_keys', ['bot_id'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_bot_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
