"""add bots table

Revision ID: a1b2c3d4e5f6
Revises: 6998a682b470
Create Date: 2026-08-18 09:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '6998a682b470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='FK lógica a users.id (sin FK para evitar acoplamiento)'),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False, comment='Nombre del plugin de estrategia a usar'),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False, comment='True = paper trading, False = trading real'),
    sa.Column('config_json', sa.Text(), nullable=False, comment='Configuración del bot en JSON (dict serializado)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Estado: stopped | running | paused | error'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bots_user_id'), 'bots', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bots_user_id'), table_name='bots')
    op.drop_table('bots')
    # ### end Alembic commands ###
